In [5]:
import pandas as pd
from google.colab import drive
drive.mount('/content/drive')
energy_prices_df = pd.read_excel("/content/drive/MyDrive/Colab Notebooks/PfDS/Energy Prices Simão :)/dgeg-ped-1985-2025-s2_pt.xlsx")

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [6]:

energy_prices_df

,Unnamed: 0,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,Unnamed: 10,Unnamed: 11,Unnamed: 12,Unnamed: 13,Unnamed: 14,Unnamed: 15
0,Direção Geral de Energia e Geologia,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Direção de Serviços de Planeamento Energético ...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,Divisão de Estatística e Mercados,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,NaN,NaN,NaN,NaN,Preços Médios de Energia Elétrica no Setor Dom...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,NaN,NaN,NaN,NaN,Diretiva 90/377/CEE do Conselho de 29 de Junho...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8,Ano,2007,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9,Sem,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
10,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
11,Preço Médio,Tipo de Consumidor,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
12,NaN,DA,NaN,NaN,DB,NaN,NaN,DC,NaN,NaN,DD,NaN,NaN,DE,NaN,NaN
13,País,Sem Taxas,Sem IVA,Com Taxas,Sem Taxas,Sem IVA,Com Taxas,Sem Taxas,Sem IVA,Com Taxas,Sem Taxas,Sem IVA,Com Taxas,Sem Taxas,Sem IVA,Com Taxas
14,Alemanha,0.2276,0.2481,0.2953,0.1813,0.2018,0.2402,0.1433,0.1638,0.1949,0.1313,0.1518,0.1806,0.0841,0.1046,0.1245
15,Áustria,0.152,0.1936,0.2324,0.1275,0.1567,0.188,0.105,0.1288,0.1545,0.0974,0.1174,0.1409,0.0763,0.0942,0.113
16,Bélgica,0.1992,0.2069,0.2503,0.1601,0.1679,0.2031,0.1229,0.1307,0.1581,0.115,0.1228,0.1486,0.0867,0.0945,0.1143
17,Bulgária,0.0562,0.0562,0.067,0.0532,0.0532,0.0639,0.0547,0.0547,0.066,0.0562,0.0562,0.0675,0.0573,0.0573,0.069
18,Chipre,0.1307,0.1329,0.1527,0.1252,0.1274,0.1461,0.1177,0.12,0.1376,0.1165,0.1188,0.1362,0.0875,0.0897,0.1029
19,Dinamarca,0.223,0.3124,0.3905,0.1589,0.2482,0.3103,0.117,0.2063,0.2579,0.1047,0.194,0.2425,0.0985,0.1878,0.2348
20,Eslováquia,0.1983,0.1983,0.2357,0.1537,0.1537,0.1827,0.1292,0.1292,0.1537,0.1022,0.1022,0.1211,0.0791,0.0791,0.0941
21,Eslovénia,0.115,0.115,0.138,0.1007,0.1007,0.1208,0.0887,0.0887,0.1064,0.0807,0.0807,0.0968,0.0636,0.0636,0.0764
22,Espanha,0.1237,0.13,0.1467,0.1237,0.13,0.1467,0.1004,0.1056,0.1225,0.0927,0.0975,0.1131,0.0689,0.0724,0.084
23,Estónia,0.0768,0.0768,0.0906,0.0649,0.0649,0.0766,0.0635,0.0635,0.075,0.0615,0.0615,0.0725,0.0575,0.0575,0.0679
24,Finlândia,0.1683,0.1758,0.2144,0.1169,0.1244,0.1517,0.0877,0.0951,0.116,0.074,0.0814,0.0993,0.0563,0.0637,0.0777
25,França,0.1305,0.1463,0.1698,0.1132,0.1276,0.15,0.0921,0.1046,0.1211,0.0887,0.1009,0.1174,0.0726,0.0834,0.0969
26,Grécia,0.0849,0.0849,0.0925,0.0774,0.0774,0.0844,0.0661,0.0661,0.072,0.0783,0.0783,0.0853,0.0598,0.0598,0.0652
27,Holanda,0.244,0.147,0.175,0.18,0.168,0.199,0.14,0.183,0.218,0.13,0.188,0.223,0.093,0.143,0.17
28,Hungria,0.119,0.119,0.1427,0.119,0.119,0.1427,0.1019,0.1019,0.1222,0.1049,0.1049,0.1258,0.0829,0.0829,0.0995
29,Irlanda,0.3056,0.3056,0.3468,0.2245,0.2245,0.2548,0.1465,0.1465,0.1662,0.1332,0.1332,0.1512,0.094,0.094,0.1067
30,Itália,0.0938,0.1164,0.128,0.0967,0.1193,0.1312,0.1658,0.2117,0.2329,0.1538,0.1997,0.2197,NaN,NaN,NaN
31,Letónia,0.0583,0.0583,0.0688,0.0583,0.0583,0.0688,0.0583,0.0583,0.0688,0.0583,0.0583,0.0688,0.0481,0.0481,0.0567
32,Lituânia,0.0811,0.0811,0.0957,0.0811,0.0811,0.0957,0.0658,0.0658,0.0776,0.0671,0.0671,0.0792,0.0503,0.0503,0.0594
33,Luxemburgo,0.2752,0.2832,0.3002,0.2059,0.2139,0.2267,0.1509,0.1589,0.1684,0.1384,0.1464,0.1552,0.0918,0.0998,0.1058
34,Malta,0.0444,0.0444,0.0466,0.0563,0.0563,0.0592,0.094,0.094,0.0987,0.1192,0.1192,0.1252,0.1408,0.1408,0.1478
35,Polónia,0.118,0.1231,0.1502,0.1155,0.1207,0.1472,0.0945,0.0997,0.1216,0.0925,0.0977,0.1192,0.0621,0.0673,0.082
36,Portugal,0.146,0.147,0.155,0.165,0.166,0.174,0.142,0.143,0.15,0.127,0.127,0.133,0.092,0.092,0.097
37,Reino Unido,0.1758,0.1758,0.1845,0.1599,0.1599,0.1679,0.1254,0.1254,0.1316,0.1254,0.1254,0.1317,0.0825,0.0825,0.0865
38,República Checa,0.1652,0.1652,0.1965,0.1462,0.1462,0.1739,0.0898,0.0898,0.1067,0.0729,0.0729,0.0866,0.0596,0.0596,0.0711
39,Roménia,0.0452,0.0452,0.0538,0.0933,0.0933,0.111,0.0855,0.0855,0.1017,0.0833,0.0833,0.0991,0.0648,0.0648,0.0771
40,Suécia,0.241,0.2693,0.3366,0.1612,0.1894,0.2369,0.1088,0.1371,0.1714,0.0964,0.1247,0.1557,0.0856,0.1139,0.1423
41,Europa 15,0.1701,0.1812,0.2098,0.143,0.1564,0.1808,0.1205,0.1374,0.1581,0.1134,0.1306,0.1502,0.086,0.1025,0.118
42,Europa 25,0.1669,0.1772,0.2056,0.1412,0.1537,0.178,0.1183,0.1339,0.1544,0.1112,0.1271,0.1466,0.0844,0.0996,0.1149
43,Europa 27,0.1641,0.1742,0.2022,0.1396,0.1518,0.1759,0.1173,0.1325,0.153,0.1104,0.1259,0.1452,0.0839,0.0988,0.114
44,Zona Euro,0.1621,0.1727,0.2015,0.1375,0.1511,0.1763,0.1203,0.1384,0.1605,0.1122,0.1307,0.1516,0.0865,0.1041,0.1204
45,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
46,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
47,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
48,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
49,NaN,Consumidor-Tipo,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
50,NaN,DA,NaN,NaN,DB,NaN,NaN,DC,NaN,NaN,DD,NaN,NaN,DE,NaN,NaN
51,Consumo anual em kWh até ao 1º semeste de 2007,600,NaN,NaN,1200,NaN,NaN,3500,NaN,NaN,7500,NaN,NaN,20000,NaN,NaN
52,Esta informação resulta do estipulado na Diret...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
53,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
54,Fonte: Eurostat,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
55,"Nota: Consumidor-Tipo DC, consumidor de referê...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
56,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
57,Fiscalidade em Portugal:,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
58,Taxa de IVA: 6% até 30 de setembro de 2011,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [14]:
print(energy_prices_df.columns.tolist())

['Unnamed: 0', 'Unnamed: 1', 'Unnamed: 2', 'Unnamed: 3', 'Unnamed: 4', 'Unnamed: 5', 'Unnamed: 6', 'Unnamed: 7', 'Unnamed: 8', 'Unnamed: 9', 'Unnamed: 10', 'Unnamed: 11', 'Unnamed: 12', 'Unnamed: 13', 'Unnamed: 14', 'Unnamed: 15']

In [15]:
print(energy_prices_df.isnull().sum())

Unnamed: 0     15
Unnamed: 1     20
Unnamed: 2     27
Unnamed: 3     27
Unnamed: 4     22
Unnamed: 5     27
Unnamed: 6     27
Unnamed: 7     24
Unnamed: 8     27
Unnamed: 9     27
Unnamed: 10    24
Unnamed: 11    27
Unnamed: 12    27
Unnamed: 13    25
Unnamed: 14    28
Unnamed: 15    28
dtype: int64

In [17]:
#The portugal data comes in a seperate sheet and 15 lines deep
energy_prices_df2 = pd.read_excel(
    "/content/drive/MyDrive/Colab Notebooks/PfDS/Energy Prices Simão :)/dgeg-ped-1985-2025-s2_pt.xlsx",
    sheet_name="Preços Médios em Portugal",
    skiprows=15
)

In [18]:
energy_prices_df2

     Unnamed: 0      Mínimo    Máximo Unnamed: 3 Unnamed: 4 Unnamed: 5
0    Banda - DA     < 1 000       NaN   0.300712   0.426013   0.484861
1    Banda - DB     ≥ 1 000   < 2 500   0.186316   0.247183   0.277272
2    Banda - DC     ≥ 2 500   < 5 000   0.162492   0.212113   0.243458
3    Banda - DD     ≥ 5 000  < 15 000   0.148553   0.192992   0.230212
4    Banda - DE    ≥ 15 000       NaN   0.141801   0.186251   0.228235
..          ...         ...       ...        ...        ...        ...
233  Banda - DA     < 1 000       NaN     0.1871     0.3105     0.3819
234  Banda - DB        1000     <2500      0.133     0.2078     0.2556
235  Banda - DC        2500     <5000     0.1239     0.1911      0.235
236  Banda - DD        5000    <15000      0.119     0.1822     0.2242
237  Banda - DE  > = 15 000       NaN     0.1166     0.1751     0.2154

[238 rows x 6 columns]

In [19]:
energy_prices_df2.columns = [
    "Banda",
    "Consumo_Min",
    "Consumo_Max",
    "Preco_Sem_Impostos",
    "Preco_Sem_IVA",
    "Preco_Final"
]

print(energy_prices_df2)

          Banda Consumo_Min Consumo_Max Preco_Sem_Impostos Preco_Sem_IVA  \
0    Banda - DA     < 1 000         NaN           0.300712      0.426013
1    Banda - DB     ≥ 1 000     < 2 500           0.186316      0.247183
2    Banda - DC     ≥ 2 500     < 5 000           0.162492      0.212113
3    Banda - DD     ≥ 5 000    < 15 000           0.148553      0.192992
4    Banda - DE    ≥ 15 000         NaN           0.141801      0.186251
..          ...         ...         ...                ...           ...
233  Banda - DA     < 1 000         NaN             0.1871        0.3105
234  Banda - DB        1000       <2500              0.133        0.2078
235  Banda - DC        2500       <5000             0.1239        0.1911
236  Banda - DD        5000      <15000              0.119        0.1822
237  Banda - DE  > = 15 000         NaN             0.1166        0.1751

    Preco_Final
0      0.484861
1      0.277272
2      0.243458
3      0.230212
4      0.228235
..          ...
233      0.3819
234      0.2556
235       0.235
236      0.2242
237      0.2154

[238 rows x 6 columns]

In [20]:
print(energy_prices_df2.isnull().sum())

Banda                  96
Consumo_Min           100
Consumo_Max           159
Preco_Sem_Impostos    100
Preco_Sem_IVA         119
Preco_Final           119
dtype: int64

In [21]:
energy_prices_df2.shape

(238, 6)

In [22]:
energy_prices_df2.head(10)

,Banda,Consumo_Min,Consumo_Max,Preco_Sem_Impostos,Preco_Sem_IVA,Preco_Final
0,Banda - DA,< 1 000,NaN,0.300712,0.426013,0.484861
1,Banda - DB,≥ 1 000,< 2 500,0.186316,0.247183,0.277272
2,Banda - DC,≥ 2 500,< 5 000,0.162492,0.212113,0.243458
3,Banda - DD,≥ 5 000,< 15 000,0.148553,0.192992,0.230212
4,Banda - DE,≥ 15 000,NaN,0.141801,0.186251,0.228235
5,NaN,NaN,NaN,NaN,NaN,NaN
6,NaN,NaN,NaN,NaN,NaN,NaN
7,1º Semestre de 2025,NaN,NaN,NaN,NaN,NaN
8,NaN,NaN,NaN,NaN,NaN,NaN
9,Bandas de consumo,Consumo anual de eletricidade (kWh),NaN,Preços em €/kWh,NaN,NaN

In [23]:
#Toremove the lines that contain just titles or blank lines
clean_df = energy_prices_df2[energy_prices_df2["Banda"].astype(str).str.contains("Banda -")]
clean_df.head(10)

,Banda,Consumo_Min,Consumo_Max,Preco_Sem_Impostos,Preco_Sem_IVA,Preco_Final
0,Banda - DA,< 1 000,NaN,0.300712,0.426013,0.484861
1,Banda - DB,≥ 1 000,< 2 500,0.186316,0.247183,0.277272
2,Banda - DC,≥ 2 500,< 5 000,0.162492,0.212113,0.243458
3,Banda - DD,≥ 5 000,< 15 000,0.148553,0.192992,0.230212
4,Banda - DE,≥ 15 000,NaN,0.141801,0.186251,0.228235
12,Banda - DA,< 1 000,NaN,0.307868,0.440103,0.501278
13,Banda - DB,≥ 1 000,< 2 500,0.181764,0.240971,0.270731
14,Banda - DC,≥ 2 500,< 5 000,0.159005,0.206963,0.23902
15,Banda - DD,≥ 5 000,< 15 000,0.146642,0.189713,0.226979
16,Banda - DE,≥ 15 000,NaN,0.142309,0.186498,0.228429

In [24]:
year = 2025
years = []
for i in range(len(clean_df)):
    years.append(year)
    if(i + 1)%10== 0:
        year -= 1

clean_df["Ano"]= years

/tmp/ipykernel_14029/319894826.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  clean_df["Ano"]= years

In [25]:
clean_df.head(20)

,Banda,Consumo_Min,Consumo_Max,Preco_Sem_Impostos,Preco_Sem_IVA,Preco_Final,Ano
0,Banda - DA,< 1 000,NaN,0.300712,0.426013,0.484861,2025
1,Banda - DB,≥ 1 000,< 2 500,0.186316,0.247183,0.277272,2025
2,Banda - DC,≥ 2 500,< 5 000,0.162492,0.212113,0.243458,2025
3,Banda - DD,≥ 5 000,< 15 000,0.148553,0.192992,0.230212,2025
4,Banda - DE,≥ 15 000,NaN,0.141801,0.186251,0.228235,2025
12,Banda - DA,< 1 000,NaN,0.307868,0.440103,0.501278,2025
13,Banda - DB,≥ 1 000,< 2 500,0.181764,0.240971,0.270731,2025
14,Banda - DC,≥ 2 500,< 5 000,0.159005,0.206963,0.23902,2025
15,Banda - DD,≥ 5 000,< 15 000,0.146642,0.189713,0.226979,2025
16,Banda - DE,≥ 15 000,NaN,0.142309,0.186498,0.228429,2025
24,Banda - DA,< 1 000,NaN,0.297549,0.410832,0.468636,2024
25,Banda - DB,≥ 1 000,< 2 500,0.186827,0.251784,0.287724,2024
26,Banda - DC,≥ 2 500,< 5 000,0.16927,0.222466,0.262605,2024
27,Banda - DD,≥ 5 000,< 15 000,0.159749,0.207786,0.251277,2024
28,Banda - DE,≥ 15 000,NaN,0.154069,0.201768,0.247565,2024
36,Banda - DA,< 1 000,NaN,0.290864,0.34485,0.393129,2024
37,Banda - DB,≥ 1 000,< 2 500,0.201286,0.230211,0.263227,2024
38,Banda - DC,≥ 2 500,< 5 000,0.182322,0.204749,0.242554,2024
39,Banda - DD,≥ 5 000,< 15 000,0.171101,0.191552,0.232124,2024
40,Banda - DE,≥ 15 000,NaN,0.167178,0.189019,0.231758,2024

In [26]:
clean_df = clean_df.drop(columns = ["Preco_Sem_IVA", "Preco_Sem_Impostos"])
clean_df

          Banda Consumo_Min Consumo_Max Preco_Final   Ano
0    Banda - DA     < 1 000         NaN    0.484861  2025
1    Banda - DB     ≥ 1 000     < 2 500    0.277272  2025
2    Banda - DC     ≥ 2 500     < 5 000    0.243458  2025
3    Banda - DD     ≥ 5 000    < 15 000    0.230212  2025
4    Banda - DE    ≥ 15 000         NaN    0.228235  2025
..          ...         ...         ...         ...   ...
233  Banda - DA     < 1 000         NaN      0.3819  2016
234  Banda - DB        1000       <2500      0.2556  2016
235  Banda - DC        2500       <5000       0.235  2016
236  Banda - DD        5000      <15000      0.2242  2016
237  Banda - DE  > = 15 000         NaN      0.2154  2016

[100 rows x 5 columns]

In [27]:
clean_df["Consumo_Max"] = clean_df["Consumo_Max"].fillna("Sem limite")

In [38]:
clean_df = clean_df.sort_values("Ano", ascending = False)
clean_df

                                        Preco_Final
Ano  Banda      Consumo_Min Consumo_Max
2025 Banda - DD ≥ 5 000     < 15 000       0.228595
     Banda - DE ≥ 15 000    Sem limite     0.228332
     Banda - DA < 1 000     Sem limite      0.49307
     Banda - DC ≥ 2 500     < 5 000        0.241239
     Banda - DB ≥ 1 000     < 2 500        0.274001
2024 Banda - DB ≥ 1 000     < 2 500        0.275475
     Banda - DE ≥ 15 000    Sem limite     0.239661
     Banda - DA < 1 000     Sem limite     0.430883
     Banda - DC ≥ 2 500     < 5 000         0.25258
     Banda - DD ≥ 5 000     < 15 000       0.241701
2023 Banda - DE ≥ 15 000    Sem limite     0.214041
     Banda - DC ≥ 2 500     < 5 000        0.218317
     Banda - DB ≥ 1 000     < 2 500        0.235393
     Banda - DA < 1 000     Sem limite     0.374706
     Banda - DD ≥ 5 000     < 15 000       0.212766
2022 Banda - DA < 1 000     Sem limite      0.42129
     Banda - DC ≥ 2 500     < 5 000        0.221047
     Banda - DD ≥ 5 000     < 15 000       0.211518
     Banda - DB ≥ 1 000     < 2 500        0.244477
     Banda - DE ≥ 15 000    Sem limite     0.203364
2021 Banda - DB ≥ 1 000     < 2 500        0.233499
     Banda - DD ≥ 5 000     < 15 000       0.203276
     Banda - DE ≥ 15 000    Sem limite     0.195341
     Banda - DA < 1 000     Sem limite     0.410027
     Banda - DC ≥ 2 500     < 5 000        0.212954
2020 Banda - DC ≥ 2 500     < 5 000        0.212646
     Banda - DA < 1 000     Sem limite     0.388362
     Banda - DB ≥ 1 000     < 2 500        0.235297
     Banda - DD ≥ 5 000     < 15 000       0.201568
     Banda - DE ≥ 15 000    Sem limite     0.192434
2019 Banda - DC ≥ 2 500     < 5 000         0.21655
     Banda - DA < 1 000     Sem limite      0.37865
     Banda - DD ≥ 5 000     < 15 000        0.20545
     Banda - DB ≥ 1 000     < 2 500         0.23955
     Banda - DE ≥ 15 000    Sem limite      0.19575
2018 Banda - DE ≥ 15 000    Sem limite     0.204997
     Banda - DD ≥ 5 000     < 15 000       0.216358
     Banda - DA < 1 000     Sem limite     0.406974
     Banda - DB ≥ 1 000     < 2 500         0.24966
     Banda - DC ≥ 2 500     < 5 000        0.226961
2017 Banda - DC ≥ 2 500     < 5 000        0.225715
     Banda - DB ≥ 1 000     < 2 500        0.247045
     Banda - DE ≥ 15 000    Sem limite     0.213025
     Banda - DD ≥ 5 000     < 15 000       0.217377
     Banda - DA < 1 000     Sem limite     0.388118
2016 Banda - DC 2500        <5000            0.2324
     Banda - DA < 1 000     Sem limite       0.3889
     Banda - DE > = 15 000  Sem limite      0.21575
     Banda - DD 5000        <15000          0.22335
     Banda - DB 1000        <2500            0.2526

In [41]:
clean_df

                                        Preco_Final
Ano  Banda      Consumo_Min Consumo_Max
2025 Banda - DD ≥ 5 000     < 15 000       0.228595
     Banda - DE ≥ 15 000    Sem limite     0.228332
     Banda - DA < 1 000     Sem limite      0.49307
     Banda - DC ≥ 2 500     < 5 000        0.241239
     Banda - DB ≥ 1 000     < 2 500        0.274001
2024 Banda - DB ≥ 1 000     < 2 500        0.275475
     Banda - DE ≥ 15 000    Sem limite     0.239661
     Banda - DA < 1 000     Sem limite     0.430883
     Banda - DC ≥ 2 500     < 5 000         0.25258
     Banda - DD ≥ 5 000     < 15 000       0.241701
2023 Banda - DE ≥ 15 000    Sem limite     0.214041
     Banda - DC ≥ 2 500     < 5 000        0.218317
     Banda - DB ≥ 1 000     < 2 500        0.235393
     Banda - DA < 1 000     Sem limite     0.374706
     Banda - DD ≥ 5 000     < 15 000       0.212766
2022 Banda - DA < 1 000     Sem limite      0.42129
     Banda - DC ≥ 2 500     < 5 000        0.221047
     Banda - DD ≥ 5 000     < 15 000       0.211518
     Banda - DB ≥ 1 000     < 2 500        0.244477
     Banda - DE ≥ 15 000    Sem limite     0.203364
2021 Banda - DB ≥ 1 000     < 2 500        0.233499
     Banda - DD ≥ 5 000     < 15 000       0.203276
     Banda - DE ≥ 15 000    Sem limite     0.195341
     Banda - DA < 1 000     Sem limite     0.410027
     Banda - DC ≥ 2 500     < 5 000        0.212954
2020 Banda - DC ≥ 2 500     < 5 000        0.212646
     Banda - DA < 1 000     Sem limite     0.388362
     Banda - DB ≥ 1 000     < 2 500        0.235297
     Banda - DD ≥ 5 000     < 15 000       0.201568
     Banda - DE ≥ 15 000    Sem limite     0.192434
2019 Banda - DC ≥ 2 500     < 5 000         0.21655
     Banda - DA < 1 000     Sem limite      0.37865
     Banda - DD ≥ 5 000     < 15 000        0.20545
     Banda - DB ≥ 1 000     < 2 500         0.23955
     Banda - DE ≥ 15 000    Sem limite      0.19575
2018 Banda - DE ≥ 15 000    Sem limite     0.204997
     Banda - DD ≥ 5 000     < 15 000       0.216358
     Banda - DA < 1 000     Sem limite     0.406974
     Banda - DB ≥ 1 000     < 2 500         0.24966
     Banda - DC ≥ 2 500     < 5 000        0.226961
2017 Banda - DC ≥ 2 500     < 5 000        0.225715
     Banda - DB ≥ 1 000     < 2 500        0.247045
     Banda - DE ≥ 15 000    Sem limite     0.213025
     Banda - DD ≥ 5 000     < 15 000       0.217377
     Banda - DA < 1 000     Sem limite     0.388118
2016 Banda - DC 2500        <5000            0.2324
     Banda - DA < 1 000     Sem limite       0.3889
     Banda - DE > = 15 000  Sem limite      0.21575
     Banda - DD 5000        <15000          0.22335
     Banda - DB 1000        <2500            0.2526

In [42]:
clean_df_da = (
    clean_df
    .reset_index()
    .query("Banda == 'Banda - DC'")#referenciar estatisticas da erce
)

In [45]:
clean_df_da = clean_df_da.drop(columns = ['Consumo_Min','Consumo_Max'])

In [46]:
clean_df_da

     Ano       Banda Preco_Final
3   2025  Banda - DC    0.241239
8   2024  Banda - DC     0.25258
11  2023  Banda - DC    0.218317
16  2022  Banda - DC    0.221047
24  2021  Banda - DC    0.212954
25  2020  Banda - DC    0.212646
30  2019  Banda - DC     0.21655
39  2018  Banda - DC    0.226961
40  2017  Banda - DC    0.225715
45  2016  Banda - DC      0.2324

In [48]:
clean_df_da.to_parquet("/content/drive/MyDrive/Colab Notebooks/PfDS/Energy Prices Simão :)/energy_prices.parquet")