In [2]:
import pandas as pd

In [1]:
from google.colab import drive
drive.mount('/content/drive', force_remount=True)
path = '/content/drive/MyDrive/Colab Notebooks/PfDS/Energy Efficiency Madalena :)/'
df2015= pd.read_csv(path + 'EstatisticasSCE_2015.csv', encoding='utf-16')
df2016= pd.read_csv(path + 'EstatisticasSCE_2016.csv', encoding='utf-16')
df2017= pd.read_csv(path + 'EstatisticasSCE_2017.csv', encoding='utf-16')
df2018= pd.read_csv(path + 'EstatisticasSCE_2018.csv', encoding='utf-16')
df2019= pd.read_csv(path + 'EstatisticasSCE_2019.csv', encoding='utf-16')
df2020= pd.read_csv(path + 'EstatisticasSCE_2020.csv', encoding='utf-16')
df2021= pd.read_csv(path + 'EstatisticasSCE_2021.csv', encoding='utf-16')
df2022= pd.read_csv(path + 'EstatisticasSCE_2022.csv', encoding='utf-16')
df2023= pd.read_csv(path + 'EstatisticasSCE_2023.csv', encoding='utf-16')
df2024Q1= pd.read_csv(path + 'EstatisticasSCE_2024Q1.csv', encoding='utf-16')
df2024Q2= pd.read_csv(path + 'EstatisticasSCE_2024Q2.csv', encoding='utf-16')
df2024Q3= pd.read_csv(path + 'EstatisticasSCE_2024Q3.csv', encoding='utf-16')
df2024Q4= pd.read_csv(path + 'EstatisticasSCE_2024Q4.csv', encoding='utf-16')
df2025Q1= pd.read_csv(path + 'EstatisticasSCE_2025Q1.csv', encoding='utf-16')
df2025Q2= pd.read_csv(path + 'EstatisticasSCE_2025Q2.csv', encoding='utf-16')
df2025Q3= pd.read_csv(path + 'EstatisticasSCE_2025Q3.csv', encoding='utf-16')
df2025Q4= pd.read_csv(path + 'EstatisticasSCE_2025Q4.csv', encoding='utf-16')

MessageError: Error: credential propagation was unsuccessful

In [ ]:
df2015.shape

(28173, 11)

In [ ]:
df2016.shape

(29920, 11)

In [ ]:
df2017.shape

(32642, 11)

In [ ]:
df2018.shape

(34149, 11)

In [ ]:
df2019.shape

(35698, 11)

In [ ]:
df2020.shape

(35913, 11)

In [ ]:
df2021.shape

(34855, 11)

In [ ]:
df2022.shape

(37605, 11)

In [ ]:
df2023.shape

(38682, 11)

In [ ]:
df2023.shape

(38682, 11)

In [ ]:
df2024Q1.shape

(9802, 11)

In [ ]:
df2024Q2.shape

(9709, 11)

In [ ]:
df2024Q3.shape

(9420, 11)

In [ ]:
df2024Q4.shape

(9991, 11)

In [ ]:
df2025Q1.shape

(9827, 11)

In [ ]:
df2025Q2.shape

(9728, 11)

In [ ]:
df2025Q3.shape

(9647, 11)

In [ ]:
df2025Q4.shape

(9851, 11)

In [ ]:
df2015.columns

Index(['Mês de Emissão', 'Região', 'NUTS III', 'Distrito', 'Concelho',
       'Tipo de Doc / Contexto', 'Tipo de Edifício', 'Classe Energética',
       'Total de Emissões CO2', 'Área Média Útil de Pavimento',
       'Total de Certificados Emitidos'],
      dtype='object')

In [ ]:
df2016.columns

Index(['Mês de Emissão', 'Região', 'NUTS III', 'Distrito', 'Concelho',
       'Tipo de Doc / Contexto', 'Tipo de Edifício', 'Classe Energética',
       'Total de Emissões CO2', 'Área Média Útil de Pavimento',
       'Total de Certificados Emitidos'],
      dtype='object')

In [ ]:
df2017.columns

Index(['Mês de Emissão', 'Região', 'NUTS III', 'Distrito', 'Concelho',
       'Tipo de Doc / Contexto', 'Tipo de Edifício', 'Classe Energética',
       'Total de Emissões CO2', 'Área Média Útil de Pavimento',
       'Total de Certificados Emitidos'],
      dtype='object')

In [ ]:
df2018.columns

Index(['Mês de Emissão', 'Região', 'NUTS III', 'Distrito', 'Concelho',
       'Tipo de Doc / Contexto', 'Tipo de Edifício', 'Classe Energética',
       'Total de Emissões CO2', 'Área Média Útil de Pavimento',
       'Total de Certificados Emitidos'],
      dtype='object')

In [ ]:
df2019.columns

Index(['Mês de Emissão', 'Região', 'NUTS III', 'Distrito', 'Concelho',
       'Tipo de Doc / Contexto', 'Tipo de Edifício', 'Classe Energética',
       'Total de Emissões CO2', 'Área Média Útil de Pavimento',
       'Total de Certificados Emitidos'],
      dtype='object')

In [ ]:
df2020.columns

Index(['Mês de Emissão', 'Região', 'NUTS III', 'Distrito', 'Concelho',
       'Tipo de Doc / Contexto', 'Tipo de Edifício', 'Classe Energética',
       'Total de Emissões CO2', 'Área Média Útil de Pavimento',
       'Total de Certificados Emitidos'],
      dtype='object')

In [ ]:
df2021.columns

Index(['Mês de Emissão', 'Região', 'NUTS III', 'Distrito', 'Concelho',
       'Tipo de Doc / Contexto', 'Tipo de Edifício', 'Classe Energética',
       'Total de Emissões CO2', 'Área Média Útil de Pavimento',
       'Total de Certificados Emitidos'],
      dtype='object')

In [ ]:
df2022.columns

Index(['Mês de Emissão', 'Região', 'NUTS III', 'Distrito', 'Concelho',
       'Tipo de Doc / Contexto', 'Tipo de Edifício', 'Classe Energética',
       'Total de Emissões CO2', 'Área Média Útil de Pavimento',
       'Total de Certificados Emitidos'],
      dtype='object')

In [ ]:
df2023.columns

Index(['Mês de Emissão', 'Região', 'NUTS III', 'Distrito', 'Concelho',
       'Tipo de Doc / Contexto', 'Tipo de Edifício', 'Classe Energética',
       'Total de Emissões CO2', 'Área Média Útil de Pavimento',
       'Total de Certificados Emitidos'],
      dtype='object')

In [ ]:
df2024Q1.columns

Index(['Mês de Emissão', 'Região', 'NUTS III', 'Distrito', 'Concelho',
       'Tipo de Doc / Contexto', 'Tipo de Edifício', 'Classe Energética',
       'Total de Emissões CO2', 'Área Média Útil de Pavimento',
       'Total de Certificados Emitidos'],
      dtype='object')

In [ ]:
df2024Q2.columns

Index(['Mês de Emissão', 'Região', 'NUTS III', 'Distrito', 'Concelho',
       'Tipo de Doc / Contexto', 'Tipo de Edifício', 'Classe Energética',
       'Total de Emissões CO2', 'Área Média Útil de Pavimento',
       'Total de Certificados Emitidos'],
      dtype='object')

In [ ]:
df2024Q3.columns

Index(['Mês de Emissão', 'Região', 'NUTS III', 'Distrito', 'Concelho',
       'Tipo de Doc / Contexto', 'Tipo de Edifício', 'Classe Energética',
       'Total de Emissões CO2', 'Área Média Útil de Pavimento',
       'Total de Certificados Emitidos'],
      dtype='object')

In [ ]:
df2024Q4.columns

Index(['Mês de Emissão', 'Região', 'NUTS III', 'Distrito', 'Concelho',
       'Tipo de Doc / Contexto', 'Tipo de Edifício', 'Classe Energética',
       'Total de Emissões CO2', 'Área Média Útil de Pavimento',
       'Total de Certificados Emitidos'],
      dtype='object')

In [ ]:
df2025Q1.columns

Index(['Mês de Emissão', 'Região', 'NUTS III', 'Distrito', 'Concelho',
       'Tipo de Doc / Contexto', 'Tipo de Edifício', 'Classe Energética',
       'Total de Emissões CO2', 'Área Média Útil de Pavimento',
       'Total de Certificados Emitidos'],
      dtype='object')

In [ ]:
df2025Q2.columns

Index(['Mês de Emissão', 'Região', 'NUTS III', 'Distrito', 'Concelho',
       'Tipo de Doc / Contexto', 'Tipo de Edifício', 'Classe Energética',
       'Total de Emissões CO2', 'Área Média Útil de Pavimento',
       'Total de Certificados Emitidos'],
      dtype='object')

In [ ]:
df2025Q3.columns

Index(['Mês de Emissão', 'Região', 'NUTS III', 'Distrito', 'Concelho',
       'Tipo de Doc / Contexto', 'Tipo de Edifício', 'Classe Energética',
       'Total de Emissões CO2', 'Área Média Útil de Pavimento',
       'Total de Certificados Emitidos'],
      dtype='object')

In [ ]:
df2025Q4.columns

Index(['Mês de Emissão', 'Região', 'NUTS III', 'Distrito', 'Concelho',
       'Tipo de Doc / Contexto', 'Tipo de Edifício', 'Classe Energética',
       'Total de Emissões CO2', 'Área Média Útil de Pavimento',
       'Total de Certificados Emitidos'],
      dtype='object')

In [ ]:
df2015_2025=pd.concat([df2015, df2016, df2017, df2018, df2019, df2020, df2021, df2022, df2023, df2024Q1, df2024Q2, df2024Q3, df2024Q4, df2025Q1, df2025Q2, df2025Q3, df2025Q4], ignore_index=True)

In [ ]:
df2015_2025.columns

Index(['Mês de Emissão', 'Região', 'NUTS III', 'Distrito', 'Concelho',
       'Tipo de Doc / Contexto', 'Tipo de Edifício', 'Classe Energética',
       'Total de Emissões CO2', 'Área Média Útil de Pavimento',
       'Total de Certificados Emitidos'],
      dtype='object')

In [ ]:
df2015_2025.shape

(385612, 11)

In [ ]:
df2015_2025.head()

,Mês de Emissão,Região,NUTS III,Distrito,Concelho,Tipo de Doc / Contexto,Tipo de Edifício,Classe Energética,Total de Emissões CO2,Área Média Útil de Pavimento,Total de Certificados Emitidos
0,2015-01,Portugal Continental,Baixo Vouga,AVEIRO,AGUEDA,Edifícios Existentes,Habitação,B,7.2000,119.500000,4
1,2015-01,Portugal Continental,Baixo Vouga,AVEIRO,AGUEDA,Edifícios Existentes,Habitação,B-,7.8100,110.997500,4
2,2015-01,Portugal Continental,Baixo Vouga,AVEIRO,AGUEDA,Edifícios Existentes,Habitação,C,31.8381,83.310833,12
3,2015-01,Portugal Continental,Baixo Vouga,AVEIRO,AGUEDA,Edifícios Existentes,Habitação,D,45.6687,99.492222,9
4,2015-01,Portugal Continental,Baixo Vouga,AVEIRO,AGUEDA,Edifícios Existentes,Habitação,F,19.6000,91.266666,3

In [ ]:
df2015_2025.isnull().sum()

Mês de Emissão                    0
Região                            0
NUTS III                          0
Distrito                          0
Concelho                          0
Tipo de Doc / Contexto            0
Tipo de Edifício                  0
Classe Energética                 0
Total de Emissões CO2             0
Área Média Útil de Pavimento      0
Total de Certificados Emitidos    0
dtype: int64

In [ ]:
df2015_2025['Tipo de Doc / Contexto'].unique()

array(['Edifícios Existentes', 'Projeto Edifícios Novos',
       'Projeto Renovação Edifícios', 'Edifícios Concluídos Novos',
       'Edifícios Concluídos Renovados'], dtype=object)

In [ ]:
df2015_2025['Tipo de Edifício'].unique()

array(['Habitação', 'Serviços'], dtype=object)

We are going to eliminate values equal to "Serviços" in column "Tipo de Edifício". Energy poverty has to do with habitational buildings only.

In [ ]:
dfclean=df2015_2025.drop(df2015_2025[df2015_2025['Tipo de Edifício'] == 'Serviços'].index)

In [ ]:
dfclean.shape

(299110, 11)

In [ ]:
dfclean['Tipo de Edifício'].unique()

array(['Habitação'], dtype=object)

In [ ]:
dfclean['Classe Energética'].unique()

array(['B', 'B-', 'C', 'D', 'F', 'A', 'E', 'A+'], dtype=object)

We dropped coluns "Total de Emissões CO2" and "Área Média Útil de Pavimento", because those are not useful for energy poverty assessment.

In [ ]:
dfclean=dfclean.drop(columns=['Total de Emissões CO2','Área Média Útil de Pavimento'])

In [ ]:
dfclean.columns

Index(['Mês de Emissão', 'Região', 'NUTS III', 'Distrito', 'Concelho',
       'Tipo de Doc / Contexto', 'Tipo de Edifício', 'Classe Energética',
       'Total de Certificados Emitidos'],
      dtype='object')

In [ ]:
dfclean['Tipo de Doc / Contexto'].value_counts()

Tipo de Doc / Contexto
Edifícios Existentes              172020
Projeto Edifícios Novos            52067
Edifícios Concluídos Novos         34433
Projeto Renovação Edifícios        28621
Edifícios Concluídos Renovados     11969
Name: count, dtype: int64

A big part of the buildings are existing buildings, which means that, in our dataframe, we have certificates of new buildings and existing buildings.
We deleted the rows about the certificate of buildings still at the project stage because these buildings do not exist yet.

In [ ]:
dfclean=dfclean.drop(dfclean[dfclean['Tipo de Doc / Contexto'] == 'Projeto Edifícios Novos'].index)
dfclean=dfclean.drop(dfclean[dfclean['Tipo de Doc / Contexto'] == 'Projeto Renovação Edifícios'].index)

In [ ]:
dfclean['Tipo de Doc / Contexto'].value_counts()

Tipo de Doc / Contexto
Edifícios Existentes              172020
Edifícios Concluídos Novos         34433
Edifícios Concluídos Renovados     11969
Name: count, dtype: int64

In [ ]:
dfclean.shape

(218422, 9)

In [ ]:
dfclean.head(20)

,Mês de Emissão,Região,NUTS III,Distrito,Concelho,Tipo de Doc / Contexto,Tipo de Edifício,Classe Energética,Total de Certificados Emitidos
0,2015-01,Portugal Continental,Baixo Vouga,AVEIRO,AGUEDA,Edifícios Existentes,Habitação,B,4
1,2015-01,Portugal Continental,Baixo Vouga,AVEIRO,AGUEDA,Edifícios Existentes,Habitação,B-,4
2,2015-01,Portugal Continental,Baixo Vouga,AVEIRO,AGUEDA,Edifícios Existentes,Habitação,C,12
3,2015-01,Portugal Continental,Baixo Vouga,AVEIRO,AGUEDA,Edifícios Existentes,Habitação,D,9
4,2015-01,Portugal Continental,Baixo Vouga,AVEIRO,AGUEDA,Edifícios Existentes,Habitação,F,3
10,2015-01,Portugal Continental,Baixo Vouga,AVEIRO,AGUEDA,Edifícios Existentes,Habitação,E,5
12,2015-01,Portugal Continental,Baixo Vouga,AVEIRO,ALBERGARIA-A-VELHA,Edifícios Existentes,Habitação,B-,3
13,2015-01,Portugal Continental,Baixo Vouga,AVEIRO,ALBERGARIA-A-VELHA,Edifícios Existentes,Habitação,D,6
15,2015-01,Portugal Continental,Baixo Vouga,AVEIRO,ALBERGARIA-A-VELHA,Edifícios Existentes,Habitação,E,6
17,2015-01,Portugal Continental,Baixo Vouga,AVEIRO,ANADIA,Edifícios Existentes,Habitação,A,3
18,2015-01,Portugal Continental,Baixo Vouga,AVEIRO,ANADIA,Edifícios Existentes,Habitação,E,6
19,2015-01,Portugal Continental,Baixo Vouga,AVEIRO,ANADIA,Edifícios Existentes,Habitação,A+,7
20,2015-01,Portugal Continental,Baixo Vouga,AVEIRO,ANADIA,Edifícios Existentes,Habitação,F,2
21,2015-01,Portugal Continental,Baixo Vouga,AVEIRO,ANADIA,Edifícios Existentes,Habitação,B,1
22,2015-01,Portugal Continental,Baixo Vouga,AVEIRO,ANADIA,Edifícios Existentes,Habitação,C,1
23,2015-01,Portugal Continental,Baixo Vouga,AVEIRO,ANADIA,Edifícios Existentes,Habitação,D,4
24,2015-01,Portugal Continental,Entre Douro e Vouga,AVEIRO,AROUCA,Edifícios Existentes,Habitação,F,1
26,2015-01,Portugal Continental,Entre Douro e Vouga,AVEIRO,AROUCA,Edifícios Existentes,Habitação,B-,1
27,2015-01,Portugal Continental,Entre Douro e Vouga,AVEIRO,AROUCA,Edifícios Existentes,Habitação,D,1
29,2015-01,Portugal Continental,Baixo Vouga,AVEIRO,AVEIRO,Edifícios Existentes,Habitação,A,2

In [ ]:
dfclean['Tipo de Edifício'].value_counts()

Tipo de Edifício
Habitação    218422
Name: count, dtype: int64

Now that all building types, are the same, we can erase this column.

In [ ]:
dfclean=dfclean.drop(columns=['Tipo de Edifício'])

In [ ]:
dfclean["Mês de Emissão"].dtype

dtype('O')

We want the dataframe to be by year and not by month.

In [ ]:
dfclean["Mês de Emissão"] = pd.to_datetime(dfclean["Mês de Emissão"])

In [ ]:
dfclean["Mês de Emissão"] = dfclean["Mês de Emissão"].dt.year

In [ ]:
df_clean=(dfclean.groupby(['Mês de Emissão', 'Região', 'NUTS III', 'Distrito', 'Concelho', 'Tipo de Doc / Contexto', 'Classe Energética'], as_index=False)['Total de Certificados Emitidos'].sum())

In [ ]:
dfclean.head(100)

,Mês de Emissão,Região,NUTS III,Distrito,Concelho,Tipo de Doc / Contexto,Classe Energética,Total de Certificados Emitidos
0,2015,Portugal Continental,Baixo Vouga,AVEIRO,AGUEDA,Edifícios Existentes,B,4
1,2015,Portugal Continental,Baixo Vouga,AVEIRO,AGUEDA,Edifícios Existentes,B-,4
2,2015,Portugal Continental,Baixo Vouga,AVEIRO,AGUEDA,Edifícios Existentes,C,12
3,2015,Portugal Continental,Baixo Vouga,AVEIRO,AGUEDA,Edifícios Existentes,D,9
4,2015,Portugal Continental,Baixo Vouga,AVEIRO,AGUEDA,Edifícios Existentes,F,3
...,...,...,...,...,...,...,...,...
162,2015,Portugal Continental,Baixo Vouga,AVEIRO,VAGOS,Edifícios Existentes,C,1
163,2015,Portugal Continental,Baixo Vouga,AVEIRO,VAGOS,Edifícios Existentes,D,4
164,2015,Portugal Continental,Baixo Vouga,AVEIRO,VAGOS,Edifícios Existentes,F,1
168,2015,Portugal Continental,Baixo Vouga,AVEIRO,VAGOS,Edifícios Existentes,E,4
169,2015,Portugal Continental,Entre Douro e Vouga,AVEIRO,VALE DE CAMBRA,Edifícios Existentes,C,5

In [ ]:
df_clean.to_parquet("/content/drive/MyDrive/Colab Notebooks/PfDS/Energy Efficiency Madalena :)/Energy_eff.parquet")